version: '3.8'

services:
  marketPlace_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketPlace
    ports:
      - "666:5432"
    volumes:
      - pg_marketPlaceNIC:/var/lib/postgresql/data
    networks:
      - app-network

  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - marketPlace_db
      - maildev
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://marketPlace_db:5432/marketPlace'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME:
      SPRING_MAIL_PASSWORD:
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: 10000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 10000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: 10000
    networks:
      - app-network

volumes:
  pg_marketPlaceNIC:

networks:
  app-network:
